SET search_path TO movie_chooser;

BEGIN WORK;

SET TRANSACTION READ WRITE;

SET datestyle = DMY;

/* MOVIE */
-- ID   TITLE   YEAR        rotten google imdb faffinity NULL     GENRE   DURATION    PLATFORM    LINK    WATCHED_SOFIA   WATCHED_ADRIAN
INSERT INTO MOVIE VALUES(1,'The Banshees of Inisherin', 2022, NULL, NULL, 7.8, NULL, NULL, 'Comedy, Drama', '01:54', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(2,'Three Billboards outside Ebbing, Missouri', 2017,  NULL, NULL, 8.1, NULL, NULL, 'Comedy, Crime, Drama', '01:55', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(3,'Snatch', 2000, NULL, NULL, 8.2, NULL, NULL, 'Comedy, Crime', '01:42', NULL, NULL, FALSE, TRUE);
INSERT INTO MOVIE VALUES(4,'The Shawshock Redemption', 1994, NULL, NULL, 9.3, NULL, NULL, 'Drama', '02:22', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(5,'The Godfather', 1972, NULL, NULL, 9.2, NULL, NULL, 'Crime, Drama', '02:55', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(6,'The Godfather II', 1974, NULL, NULL, 9.0, NULL, NULL, 'Crime, Drama', '03:22', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(7,'The Usual Suspects', 1995, NULL, NULL, 8.5, NULL, NULL, 'Crime, Drama, Mistery', '01:46', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(8,'Goodfellas', 1990, null, null, 8.7, null, null, 'Biography, Crime, Drama', '02:25', NULL, NULL,  FALSE, FALSE);
INSERT INTO MOVIE VALUES(9,'Aftersun', 2022, 8.2, NULL, NULL, NULL, NULL, 'Drama', '01:41', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(10,'Everything Everywhere All At Once', 2022, NULL, NULL, 8.0, NULL, NULL, 'Action, Adventure, Comedy', '02:19', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(11,'White Noise', 2022, NULL, NULL, 5.7, NULL, NULL, 'Comedy, Drama, Horror', '02:16', 'Netflix', NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(12,'Seven Psycopaths', 2012, NULL, NULL, 7.1, NULL, 'Comedy, Crime', '01:50', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(13,'Fire of Love', 2022, NULL, NULL, 7.6, NULL, NULL, 'Documentary, Biography', '01:38', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(14,'Scarface', 1983, NULL, NULL, 8.3, NULL, NULL, 'Crime, Drama', '02:50', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(15,'Raging Bull', 1980, NULL, NULL, 8.2, NULL, NULL, 'Biography, Drama, Sport', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(16,'Mega Shark vs. Crocosaurus', 2010, NULL, NULL, 2.4, NULL, NULL, 'Action, Adventure, Comedy', '01:28', NULL, NULL, FALSE, FALSE);
INSERT INTO MOVIE VALUES(17,'Winnie the Pooh: Blood and Honey', 2023, NULL, NULL, 4.2, NULL, NULL, 'Horror', '01:24', NULL, NULL, FALSE, FALSE);

/* DIRECTOR */
INSERT INTO DIRECTOR VALUES(1,'Martin McDonagh', '26-03-1970', NULL, 'Male', 'UK');
INSERT INTO DIRECTOR VALUES(2,'Guy Ritchie', '10-09-1968', NULL, 'Male', 'UK');
-- 3 Oliver Stone
INSERT INTO DIRECTOR VALUES(4,'Frank Darabont', '28-01-1959', NULL, 'Male', 'US');
-- 5
INSERT INTO DIRECTOR VALUES(6,'Francis Ford Coppola', '07-04-1939', NULL, 'Male', 'US');
INSERT INTO DIRECTOR VALUES(7,'Bryan Singer', '17-09-1965', NULL, 'Male', 'US');
INSERT INTO DIRECTOR VALUES(8,'Martin Scorsesse', '17-11-1942', NULL, 'Male', 'US');
INSERT INTO DIRECTOR VALUES(9,'Charlotte Welles', '13-06-1987', NULL, 'Female', 'UK');
-- 10
-- 11
-- 12
-- 13
INSERT INTO DIRECTOR VALUES(14,'Dan Kwan', '10-02-1988', NULL, 'Male', 'US');
INSERT INTO DIRECTOR VALUES(15,'Daniel Scheinert', '07-06-1987', NULL, 'Male', 'US');
INSERT INTO DIRECTOR VALUES(16,'Noah Baumbach', '03-09-1969', NULL, 'Male', 'US');
-- 17
-- 18
INSERT INTO DIRECTOR VALUES(19,'Sara Dosa', NULL, NULL, 'Female', 'US');
INSERT INTO DIRECTOR VALUES(20,'Brian De Palma', '11-09-1940', NULL, 'Male', 'US');
INSERT INTO DIRECTOR VALUES(21,'Christopher Ray', '30-07-1997', NULL, 'Male', 'US');
-- 22
INSERT INTO DIRECTOR VALUES(23 'Rhys Frake-Waterfield', NULL, NULL, 'Male', 'UK');
INSERT INTO DIRECTOR VALUES(
INSERT INTO DIRECTOR VALUES(
INSERT INTO DIRECTOR VALUES(
INSERT INTO DIRECTOR VALUES(


/* DIRECTED */
--                      MOVIE  DIRECTOR
INSERT INTO DIRECTED VALUES(1,1);
INSERT INTO DIRECTED VALUES(2,1);
INSERT INTO DIRECTED VALUES(3,2);
INSERT INTO DIRECTED VALUES(4,4);
INSERT INTO DIRECTED VALUES(5,6);
INSERT INTO DIRECTED VALUES(6,6);
INSERT INTO DIRECTED VALUES(7,7);
INSERT INTO DIRECTED VALUES(8,8);
INSERT INTO DIRECTED VALUES(9,9);
INSERT INTO DIRECTED VALUES(10,14);
INSERT INTO DIRECTED VALUES(10,15);
INSERT INTO DIRECTED VALUES(11,16);
INSERT INTO DIRECTED VALUES(12,1);
INSERT INTO DIRECTED VALUES(13,19);
INSERT INTO DIRECTED VALUES(14,20);
INSERT INTO DIRECTED VALUES(15,8);
INSERT INTO DIRECTED VALUES(16,21);
INSERT INTO DIRECTED VALUES(17,23);
INSERT INTO DIRECTED VALUES(
INSERT INTO DIRECTED VALUES(
INSERT INTO DIRECTED VALUES(
